### ISSUE TITLE
Rust-in-Flutter was renamed to Rinf

### ISSUE THREAD

**Issue by temeddix** [LucaCoduriV/Notiflut-Land#2]
Hi, I have noticed that you were creating a wonderful project here with Rust-In-Flutter :)

`rust_in_flutter` has been renamed to `rinf`, so what do you think about replacing the dependency in `pubspec.yaml`? Internal APIs remain the same, so you might only need to change some import statements.

https://pub.dev/packages/rinf

**Comment by LucaCoduriV** [comment]
Yep, I should do it. Thank you for reminding me.

**Comment by LucaCoduriV** [comment]
Hello @temeddix, I am trying to update, but it seems that I also have to regen the template with `rinf template`.
Is there any guide to be sure that I have not forget anything ?

**Comment by LucaCoduriV** [comment]
@temeddix It seems that you made a lot of changes in the rust dependencies. I am not sure to understand how to make it work again.

**Comment by LucaCoduriV** [comment]
Thank you ! :+1:
